### PR TITLE
Support input-str and lookup-input-str flags in diff inputs command

### PR DESCRIPTION
**Pull request by StephenDiligent**
This change set addresses https://github.com/simplesurance/baur/issues/232

I decided to add a new query to load task runs that contain an input with a given digest to find runs by their input-str instead of loading all task runs then iterating over them within baur. 

Example outputs from these changes:
A single run exists for baur_foo.build that contains an input-str of "master"
**run with given input-str does not exist**
image
**run with given input-str and lookup-input-str does not exist**
image
**run with given input-str does exist**
image
**run with given input-str does not exist but given lookup-input-str does exist**
image

@fho

### CODE REVIEW

**Comment by StephenDiligent** [comment]
It looks like one of the existing tests failed because it was unable to connect to the postgres DB. 
I do not have the necessary permissions to rerun the check in CircleCI.

**Comment by fho** [comment]
@StephenDiligent
thanks for the PR, I'll have a look soon.

 I rerun the test and they are still failing with `FATAL: sorry, too many clients already`.
The issues should be that we invoke in the test the command implementation which do not close the psql connections currently.
With the new change the max. number of parallel psql connections was reached.
I'll add the close calls for the psql connection.

**Comment by fho** [comment]
Sorry but I have problems to understand the change.
Could you please explain in the PR description the change, including what effect `--input-str` and `--lookup-input-str` has when specifying task, task-run ids, or task runs via the caret notation?

Please correct me if I'm wrong with my comments: :-)

The new behavior of the parameter seems inconsistent with how it works for other commands.
The usage description for `--input-str` is e.g. the same but it seems not to simply add the string as additional input for the first specified task-run/task, instead it changes the db-query?
In general the same parameter should have consistent behavior for all commands.
For example I would expect that:
`ngbaur diff inputs --input-str master random.build random.build^`
shows the difference of the inputs defined in the .app.toml file of the `random.build` task, with the additional string input `master`,  and the last recorded run of `random.build`.

It's also confusing to me that the positional parameters for `baur diff inputs` specify exactly which builds too compare.
When `--input-str` or `--lookup-input-str is passed though they to change their meaning and become queries . This behavior is  also not clearly described in the `baur diff inputs --help` output.

If you want to find the last recorded run of a task with a specific input string we might need to a new query syntax instead of changing the meaning.
Finding the last recorded task run with a specific input string might also fit well into `baur ls runs`, then the required functionality could be combined like:
```sh
run_id="$(baur ls runs --has-input-with-digest=sha256:123  --sort time-desc --csv --fields id baur_foo.build)
baur inputs diff baur_foo.build $run_id
```

**Comment by dbason** [comment]
Hi Favian,

The idea to us `baur ls runs` and then pass that along sounds fine to me.

Our core use case is that we need to compare the current state on a PR or branch against the previous build for that PR or branch.

**Comment by StephenDiligent** [comment]
I'm closing this PR in favour of adding `input-str` and `lookup-input-str` support to the `baur ls runs` command.

**Comment by fho** [comment]
Hello @dbason @StephenDiligent,

I would suggest that you describe your usecase in a new post at the [Discussions Github page](https://github.com/simplesurance/baur/discussions?discussions_q=category%3AIdeas). If you already have ideas how it could be used from the commandline please, also add those as examples.
Then we figure out a way together how we could integrate what you need before starting the implementation.

Maybe we can also find a way to do what you need via "baur diff inputs" if that is a better workflow.

@dbason Yes, I agree regarding `--has-input-with-digest`. The user should not have to calculate the digest on his own.

**Comment by dbason** [comment]
@fho I've added a discussion at https://github.com/simplesurance/baur/discussions/235

I hope that describes our process and use case in full.

**Pull request closed without merging**
