### PR TITLE
support to pass multiple --input-str parameters

### PR DESCRIPTION
**Pull request by fho**
The run, status, ls inputs, diff inputs commands now support to be passed multiple
"--input-str" parameters, each specified parameter is added as individual string
input.

### CODE REVIEW

**Review by FranciscoKurpiel — COMMENTED** [review]
If I understand correctly, the code as it is, will produce the same final hash for the inputs if I just invert the order of the `--input-str parameters` flags. For example:

```
--input-str A --input-str B
```

and

```
--input-str B --input-str A
```

**Comment by fho** [comment]
@FranciscoKurpiel yes that is correct

**Comment by FranciscoKurpiel** [comment]
> @FranciscoKurpiel yes that is correct

Imho, the order should be preserved, because I believe most frequently than not, it will hold semantic value, so if we invert the order the artifact should be rebuilt. One possible approach for that is instead of this additional inputs being just strings, they could be key-pair maps. For example:

```
--input-str branch=master --input-str mode=develop
```

**Comment by fho** [comment]
@FranciscoKurpiel 

It's possible to use `--input-strings` in both ways you mentioned because they are arbitrary and can be freely defined:
If you want use them in a way where the order matters, you could specify them as one input-string instead of multiple, like: 
`--input-str branch=master,mode=develop`.
If you want to use a key-value format, you could always specify them in a kv format, like `--input-str branch=master --input-str mode=develop`.

I think it would be counter-intuitive and would led to unexpected results if the order in which the `--input-strings` parameters are specified on the commandline would matter.
You would always have to remember in which order they were specified and ensure you specify them in the same order in all invocations, otherwise you get unexpected results

**Comment by FranciscoKurpiel** [comment]
Fair points. Would you like to proceed with this design or will you tweak more?

**Comment by fho** [comment]
@FranciscoKurpiel this PR is done :-)

**Review by FranciscoKurpiel — APPROVED** [review]

**Pull request merged**
